spring:
  application:
    name: payment-disputes-orchestration
  temporal:
    connection:
      target: 127.0.0.1:7233
    namespace: default
    workers-auto-discovery:
      packages:
        - com.posadskiy.orchestration.payment.refund
