spring:
  application:
    name: payment-disputes-orchestration
  temporal:
    connection:
      target: 127.0.0.1:7233
    namespace: default
    workers:
      - task-queue: refund-task-queue
        name: refund-worker
        workflow-classes:
          - com.posadskiy.orchestration.payment.refund.RefundWorkflowImpl
        activity-beans:
          - refundActivitiesImpl
